# Generated by Django 4.2.16 on 2024-11-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='instruction',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
